# Generated by Django 4.2.8 on 2023-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu_model',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
