# Generated by Django 4.2.8 on 2023-12-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_edu_model_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu_model',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='edu_model',
            name='category',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
