# Generated by Django 4.2.8 on 2023-12-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_model2_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='is_visible',
        ),
    ]
