# Generated by Django 4.2.8 on 2023-12-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userclass',
        ),
    ]
