# Generated by Django 4.2.8 on 2023-12-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_user_userclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
